/**
 * The photography catalog.
 *
 * One entry per photograph we may publish, with its provenance and its limits
 * recorded next to it. Templates ask for an asset by intent — "a 16:9 camping
 * photograph" — and never by path, so a slot cannot be filled by whatever
 * happened to be lying in `public/images/` when someone went looking.
 *
 * Three things this file exists to prevent, each of which has already happened
 * once on this project or was one merge away:
 *
 *  1. A photograph of the wrong machine. A file named `using_the_freeze_dryer`
 *     turned out to be a steam autoclave — opposite machine, opposite physics.
 *     Every `equipment` entry here was confirmed by looking at the frame for a
 *     vacuum chamber, a sealed door, stacked flat trays and a separate pump.
 *  2. A stock photograph of a commercial pouch standing in for our packaging.
 *     `not-product-imagery` is not advice; `tests/assets.test.mjs` fails the
 *     build if one reaches a product surface. A removed label does not make a
 *     pouch ours.
 *  3. Alt text that describes a photograph nobody has. Alt lives here, with the
 *     photograph, rather than being copied into each article that uses it —
 *     which is how `/guides/which-freeze-dryer` came to promise screen-reader
 *     users "a person loading a tray" for a frame containing no person.
 *
 * Derivatives are generated by `assets/build-derivatives.mjs` and committed.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { CATALOG } from './commerce.ts';

export type AssetClass =
  | 'product'        // our catalog items
  | 'food'           // isolated food on white
  | 'equipment'      // verified freeze dryers, trays, sealing in progress
  | 'camping'        // outdoor, trail context
  | 'process'        // packing, sealing, labeling
  | 'line-hero'      // wide, atmospheric, represents a line
  | 'brand';         // portrait, workspace

export type AssetSource = 'own' | 'manufacturer' | 'stock';

export type AssetRatio = '16:9' | '4:5' | '1:1';

/**
 * The restriction vocabulary, closed on purpose.
 *
 * A free `string[]` lets a typo become a silently unenforced rule: nothing
 * matches `'not-product-imagry'`, and the asset walks into a product card.
 */
export type AssetRestriction =
  /** Stock photography of someone else's commercial packaging. May illustrate
   *  the activity; may never represent Sublime Pantry packaging or appear in a
   *  product context. */
  | 'not-product-imagery'
  /** Editorial use only — a caption is required wherever it renders. */
  | 'editorial-illustration-only'
  /** Equipment we do not own and have not tested. The site says in print that
   *  we have bench-tested no machine; alt text and captions must not imply
   *  otherwise. */
  | 'not-our-equipment'
  /** Admitted with its source unconfirmed. Labelled conservatively until a
   *  licence record turns up. Surfaced in docs/ASSET-LIBRARY.md rather than
   *  buried in a field. */
  | 'provenance-unverified'
  /** The unit visible in frame carries a legible third brand that is not one
   *  of the machines the page reviews or compares. `not-our-equipment` alone
   *  reads as "not tested by us," which a skimming reader can still misparse
   *  as "one of the compared machines, just not our unit." */
  | 'not-a-reviewed-model';

export interface Asset {
  id: string;                 // stable kebab-case, never renamed
  src: string;                // base path; derivatives resolved by helper
  alt: string;                // what is visible, not what we wish were visible
  cls: AssetClass;
  source: AssetSource;
  credit?: string;            // 'Photo: PackFreshUSA' | 'Stock photo' | 'Illustrative'
  ratios: AssetRatio[];       // which crops were generated
  /** How the ratio was reached. 'cover' centre-crops; 'contain' scales the
   *  whole frame in and pads with white, for subjects isolated on white where
   *  a crop would cut the subject. Must match `fit` in assets/sources.json —
   *  tests/assets.test.mjs fails if the two disagree, because the width ladder
   *  is computed differently for each and a mismatch means the manifest claims
   *  files that are not there (or misses files that are). */
  fit?: 'cover' | 'contain';
  intrinsic: { w: number; h: number };
  subject: string[];          // ['strawberry','fruit'] — for matching
  /** Hard constraints. Enforced by tests, not by convention. */
  restrictions?: AssetRestriction[];
  usedBy: string[];           // populated at build; where it currently appears
}

/** Widths `assets/build-derivatives.mjs` emits, never exceeding intrinsic. */
export const DERIVATIVE_WIDTHS = [400, 800, 1600] as const;

const RATIO_VALUE: Record<AssetRatio, number> = { '16:9': 16 / 9, '4:5': 4 / 5, '1:1': 1 };

const MANIFEST: Omit<Asset, 'usedBy'>[] = [
  // ---- equipment -------------------------------------------------------
  // Both confirmed by eye: vacuum chamber, sealed round door with a gasket,
  // stacked flat trays, separate pump. Both are licensed Adobe Stock downloads
  // (kMDItemWhereFroms = stock.adobe.com), so neither is ours and neither may
  // be captioned as if we ran the batch.
  {
    id: 'freeze-dryer-door-trays-fruit',
    src: '/images/library/freeze-dryer-door-trays-fruit',
    alt: 'The clear inner door of a green home freeze dryer, closed over five stacked trays of part-dried fruit.',
    cls: 'equipment',
    source: 'stock',
    credit: 'Stock photo',
    ratios: ['16:9', '4:5', '1:1'],
    intrinsic: { w: 6000, h: 4000 },
    subject: ['freeze-dryer', 'chamber', 'trays', 'fruit', 'machines'],
    restrictions: ['not-our-equipment'],
  },
  {
    id: 'freeze-dryer-pair-loaded-trays',
    src: '/images/library/freeze-dryer-pair-loaded-trays',
    // Alt describes only what survives every generated crop. The 16:9 band
    // loses the vacuum pump and the machine bodies that the 4:5 keeps, so
    // naming the pump here would be false on one crop and true on another.
    alt: 'Two home freeze dryers side by side, one with its chamber door open on eight stacked trays of part-dried red fruit.',
    cls: 'equipment',
    source: 'stock',
    credit: 'Stock photo',
    ratios: ['16:9', '4:5', '1:1'],
    intrinsic: { w: 3845, h: 5767 },
    subject: ['freeze-dryer', 'vacuum-pump', 'trays', 'fruit', 'machines'],
    // The visible unit is branded ESTBRIGHT — not Harvest Right, Blue Alpine,
    // or Stay Fresh, the machines /compare/home-freeze-dryers actually
    // reviews. "not a Sublime Pantry test unit" alone lets a skimming reader
    // assume it's one of those three; it is not.
    restrictions: ['not-our-equipment', 'not-a-reviewed-model'],
  },

  // ---- camping ---------------------------------------------------------
  // Canva exports from our own team document, but the pouches inside them are
  // commercial stock photography. `stock`, not `own`: we did not shoot these
  // and the packaging in frame is not ours.
  {
    id: 'camp-pouch-rehydrated-chili',
    src: '/images/library/camp-pouch-rehydrated-chili',
    alt: 'Hands holding an open silver pouch of rehydrated chilli beside a camp stove on a bed of river rock.',
    cls: 'camping',
    source: 'stock',
    credit: 'Stock photo',
    ratios: ['16:9', '4:5', '1:1'],
    intrinsic: { w: 6120, h: 4084 },
    subject: ['camping', 'trail', 'pouch', 'meal', 'rehydration'],
    restrictions: ['not-product-imagery', 'editorial-illustration-only'],
  },
  {
    id: 'camp-pouch-freeze-dried-vegetables',
    src: '/images/library/camp-pouch-freeze-dried-vegetables',
    alt: 'An open silver pouch of freeze-dried green beans, peas, sweetcorn and diced carrot resting in dry grass.',
    cls: 'camping',
    source: 'stock',
    credit: 'Stock photo',
    ratios: ['16:9', '4:5', '1:1'],
    intrinsic: { w: 6016, h: 4000 },
    subject: ['camping', 'trail', 'pouch', 'vegetables'],
    restrictions: ['not-product-imagery', 'editorial-illustration-only'],
  },

  // ---- product: PackFreshUSA ------------------------------------------
  // Manufacturer studio shots. `subject` carries the SKU each belongs to, so a
  // product surface can ask for its own photographs once the Shopify product
  // is ACTIVE and has a CATALOG entry. None of these has one today.
  {
    id: 'packfresh-6x6-bag-100cc-absorbers',
    src: '/images/library/packfresh-6x6-bag-100cc-absorbers',
    alt: 'A 6 by 6 inch flat Mylar bag with rounded corners beside a sealed pack of PackFreshUSA 100cc oxygen absorbers.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['1:1'], intrinsic: { w: 1280, h: 1280 },
    subject: ['mylar-bag', '6x6', 'oxygen-absorber', '100cc', 'snack', 'SP-SNK-KIT'],
  },
  {
    id: 'packfresh-6x6-bag-dimensions',
    src: '/images/library/packfresh-6x6-bag-dimensions',
    alt: 'A 6 by 6 inch flat Mylar bag with its width and height dimensioned at 6 inches on each side.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['1:1'], intrinsic: { w: 1280, h: 1280 },
    subject: ['mylar-bag', '6x6', 'dimensions', 'snack', 'SP-SNK-KIT'],
  },
  {
    id: 'packfresh-mre-half-front',
    src: '/images/library/packfresh-mre-half-front',
    alt: 'A half-portion 7.5 mil MRE stand-up Mylar pouch, zipper closed, seen from the front.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['1:1'], intrinsic: { w: 1280, h: 1280 },
    subject: ['mre-pouch', 'half-portion', '7.5mil', 'trail', 'SP-TRL-HALF'],
  },
  {
    id: 'packfresh-mre-half-with-absorbers',
    src: '/images/library/packfresh-mre-half-with-absorbers',
    alt: 'A half-portion 7.5 mil MRE stand-up Mylar pouch beside a sealed pack of PackFreshUSA oxygen absorbers.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['1:1'], intrinsic: { w: 1280, h: 1280 },
    subject: ['mre-pouch', 'half-portion', 'oxygen-absorber', 'trail', 'SP-TRL-HALF'],
  },
  {
    id: 'packfresh-mre-half-open-interior',
    src: '/images/library/packfresh-mre-half-open-interior',
    alt: 'A half-portion MRE Mylar pouch held open, showing the unprinted silver interior and the bottom gusset.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['1:1'], intrinsic: { w: 1280, h: 1280 },
    subject: ['mre-pouch', 'half-portion', 'interior', 'trail', 'SP-TRL-HALF'],
  },
  {
    id: 'packfresh-mre-half-dimensions',
    src: '/images/library/packfresh-mre-half-dimensions',
    alt: 'A half-portion MRE stand-up Mylar pouch dimensioned at 6 inches tall by 8 inches wide.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['1:1'], intrinsic: { w: 1280, h: 1280 },
    subject: ['mre-pouch', 'half-portion', 'dimensions', 'trail', 'SP-TRL-HALF'],
  },
  {
    id: 'packfresh-mre-full-with-absorbers',
    src: '/images/library/packfresh-mre-full-with-absorbers',
    alt: 'A full-portion 7.5 mil MRE stand-up Mylar pouch beside a sealed pack of PackFreshUSA oxygen absorbers.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['1:1'], intrinsic: { w: 1280, h: 1280 },
    subject: ['mre-pouch', 'full-portion', 'oxygen-absorber', 'trail', 'SP-TRL-FULL'],
  },
  {
    id: 'packfresh-mre-full-gusset-dimensions',
    src: '/images/library/packfresh-mre-full-gusset-dimensions',
    alt: 'A full-portion MRE Mylar pouch lying on its side, its bottom gusset dimensioned at 4.5 inches.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['1:1'], intrinsic: { w: 1280, h: 1280 },
    subject: ['mre-pouch', 'full-portion', 'gusset', 'dimensions', 'trail', 'SP-TRL-FULL'],
  },
  {
    id: 'packfresh-quart-flat-with-absorbers',
    src: '/images/library/packfresh-quart-flat-with-absorbers',
    alt: 'A quart flat Mylar bag beside a sealed pack of PackFreshUSA oxygen absorbers.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['1:1'], intrinsic: { w: 1280, h: 1280 },
    subject: ['mylar-bag', 'quart', 'oxygen-absorber', 'reserve', 'SP-RSV-QUART'],
  },
  {
    id: 'packfresh-quart-flat-dimensions',
    src: '/images/library/packfresh-quart-flat-dimensions',
    alt: 'A quart flat Mylar bag dimensioned at 12 inches tall by 8 inches wide.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['1:1'], intrinsic: { w: 1280, h: 1280 },
    subject: ['mylar-bag', 'quart', 'dimensions', 'reserve', 'SP-RSV-QUART'],
  },
  {
    id: 'packfresh-mini-sealer-open',
    src: '/images/library/packfresh-mini-sealer-open',
    alt: 'A PackFreshUSA mini bag sealer standing upright with its jaws open and its cord trailing.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['4:5'], intrinsic: { w: 1152, h: 1280 },
    subject: ['sealer', 'tool', 'SP-TOOL-SEALER'],
  },
  {
    id: 'packfresh-mini-sealer-angled',
    src: '/images/library/packfresh-mini-sealer-angled',
    alt: 'A PackFreshUSA mini bag sealer seen at an angle, jaws open, showing the heating strip.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['4:5'], intrinsic: { w: 1152, h: 1280 },
    subject: ['sealer', 'tool', 'SP-TOOL-SEALER'],
  },
  {
    id: 'packfresh-mini-sealer-sealing-bag',
    src: '/images/library/packfresh-mini-sealer-sealing-bag',
    alt: 'A hand closing a PackFreshUSA mini bag sealer across the open top of a Mylar bag.',
    cls: 'product', source: 'manufacturer', credit: 'Photo: PackFreshUSA',
    ratios: ['4:5'], intrinsic: { w: 1152, h: 1280 },
    subject: ['sealer', 'tool', 'sealing', 'SP-TOOL-SEALER'],
  },

  // ---- food ------------------------------------------------------------
  // Isolated on white, professionally shot, and arriving with every scrap of
  // EXIF stripped by whoever cropped them. `own` would be a claim we cannot
  // support, so they carry the conservative label until a licence record does.
  // Re-cut from the full-resolution Adobe sheet (AdobeStock_530935565,
  // 10772x3119) by assets/extract-piles.mjs rather than from the hand-made
  // crops this library started with. Those were 200-630px — one of them could
  // not make a single declared ratio — and hand-cutting them again would have
  // produced the same class of problem at different numbers.
  //
  // `contain` in sources.json, not `cover`: every pile is wider than it is
  // tall, so a 1:1 crop would take 55% of the width off the subject. Padding is
  // invisible against a white ground.
  {
    id: 'freeze-dried-strawberry-slices-pile',
    src: '/images/library/freeze-dried-strawberry-slices-pile',
    alt: 'A pile of freeze-dried strawberry slices on white, cut faces showing pale dry centres and visible seeds.',
    cls: 'food', source: 'stock', credit: 'Stock photo',
    ratios: ['16:9', '4:5', '1:1'], fit: 'contain', intrinsic: { w: 2850, h: 1272 },
    subject: ['strawberry', 'fruit'],
    restrictions: ['provenance-unverified'],
  },
  {
    id: 'freeze-dried-blueberries-pile',
    src: '/images/library/freeze-dried-blueberries-pile',
    alt: 'A pile of whole freeze-dried blueberries on white, skins wrinkled and matte with occasional split red interiors.',
    cls: 'food', source: 'stock', credit: 'Stock photo',
    ratios: ['16:9', '4:5', '1:1'], fit: 'contain', intrinsic: { w: 2327, h: 1214 },
    subject: ['blueberry', 'fruit'],
    restrictions: ['provenance-unverified'],
  },
  {
    id: 'freeze-dried-banana-slices-pile',
    src: '/images/library/freeze-dried-banana-slices-pile',
    alt: 'Seven freeze-dried banana slices on white, pale and chalky with the seed line still visible across each cut face.',
    cls: 'food', source: 'stock', credit: 'Stock photo',
    ratios: ['16:9', '4:5', '1:1'], fit: 'contain', intrinsic: { w: 2101, h: 1265 },
    subject: ['banana', 'fruit'],
    restrictions: ['provenance-unverified'],
  },
];

/**
 * Wording a restriction obliges the caption to carry, generated rather than
 * typed.
 *
 * `/guides/which-freeze-dryer` used to spell "not a Sublime Pantry test unit"
 * into its own front matter. That works exactly until someone swaps the
 * photograph and does not copy the sentence across — and the site states in
 * print that we have bench-tested no machine, so losing it turns a true page
 * into a misleading one. Deriving it from `not-our-equipment` means the note
 * travels with the photograph and cannot be dropped by hand.
 */
const RESTRICTION_NOTE: Partial<Record<AssetRestriction, string>> = {
  'not-our-equipment': 'not a Sublime Pantry test unit',
  'not-product-imagery': 'not Sublime Pantry packaging',
  'not-a-reviewed-model': 'not one of the machines reviewed here',
};

/** The visible caption: credit first, then any note its restrictions oblige. */
export function caption(asset: Asset): string | undefined {
  const notes = (asset.restrictions ?? []).map((r) => RESTRICTION_NOTE[r]).filter(Boolean);
  const parts = [asset.credit, ...notes].filter(Boolean);
  return parts.length ? parts.join(' — ') : undefined;
}

/** `<base>/<ratio>-<width>.webp`. Mirrors `assets/build-derivatives.mjs`. */
export function derivative(asset: Asset, ratio: AssetRatio, width: number): string {
  return `${asset.src}/${ratio.replace(':', 'x')}-${width}.webp`;
}

/**
 * Widths actually emitted for a ratio — never an upscale.
 *
 * The ceiling depends on how the ratio was reached. A `cover` derivative is cut
 * out of the frame, so the ceiling is the cropped width; a `contain` one keeps
 * the whole frame and pads, so the ceiling is the intrinsic width. Getting this
 * wrong does not fail loudly: the manifest simply claims a set of files that
 * differs from what is on disk, and a `srcset` entry 404s.
 */
export function widthsFor(asset: Asset, ratio: AssetRatio): number[] {
  const { w, h } = asset.intrinsic;
  const ceiling = asset.fit === 'contain' ? w : Math.min(w, Math.round(h * RATIO_VALUE[ratio]));
  return DERIVATIVE_WIDTHS.filter((width) => width <= ceiling);
}

/** `srcset` for a ratio, widest last. Empty when the ratio was not generated. */
export function srcSet(asset: Asset, ratio: AssetRatio): string {
  if (!asset.ratios.includes(ratio)) return '';
  return widthsFor(asset, ratio)
    .map((width) => `${derivative(asset, ratio, width)} ${width}w`)
    .join(', ');
}

/** The largest generated width for a ratio — the `src` an <img> should carry. */
export function largest(asset: Asset, ratio: AssetRatio): { src: string; w: number; h: number } | null {
  if (!asset.ratios.includes(ratio)) return null;
  const widths = widthsFor(asset, ratio);
  const width = widths.at(-1);
  if (!width) return null;
  return { src: derivative(asset, ratio, width), w: width, h: Math.round(width / RATIO_VALUE[ratio]) };
}

/**
 * Where each asset currently appears, read from the two places that decide it:
 * article front matter and the commerce catalog. Computed rather than typed,
 * because a hand-maintained usage list is wrong the first time someone moves a
 * photograph and does not think to come back here.
 */
function usage(): Map<string, string[]> {
  const map = new Map<string, string[]>();
  const add = (id: string, where: string) => map.set(id, [...(map.get(id) ?? []), where]);

  const dir = join(process.cwd(), 'src/content/articles');
  if (existsSync(dir)) {
    for (const file of readdirSync(dir).filter((f) => f.endsWith('.json')).sort()) {
      const data = JSON.parse(readFileSync(join(dir, file), 'utf8')) as {
        image?: { assetId?: string };
      };
      if (data.image?.assetId) add(data.image.assetId, `article: ${file.replace(/\.json$/, '')}`);
    }
  }
  for (const product of CATALOG) {
    for (const image of product.images) {
      if (image.assetId) add(image.assetId, `product: ${product.sku}`);
    }
  }
  return map;
}

const USAGE = usage();

export const ASSETS: Asset[] = MANIFEST.map((a) => ({ ...a, usedBy: USAGE.get(a.id) ?? [] }));

const BY_ID = new Map(ASSETS.map((a) => [a.id, a]));

export function getAsset(id: string): Asset | null {
  return BY_ID.get(id) ?? null;
}

/**
 * The context a slot renders in. `product` is anything that represents
 * something we sell — a card, a PDP, a cart line. `editorial` is everything
 * else. The distinction is the whole point of `not-product-imagery`.
 */
export type AssetContext = 'product' | 'editorial';

export interface AssetQuery {
  cls?: AssetClass;
  /** Every listed subject must be present — narrowing, not widening. */
  subject?: string | string[];
  ratio?: AssetRatio;
  context?: AssetContext;
  /** Drop anything carrying any restriction at all. */
  excludeRestricted?: boolean;
}

/**
 * Assets matching every stated criterion, in manifest order.
 *
 * There is no fuzzy fallback and no "closest match". An empty result means the
 * slot renders nothing, which is the correct outcome: an article about machines
 * must never receive a photograph of fruit because the slot was open.
 */
export function findAssets(query: AssetQuery = {}): Asset[] {
  const subjects = query.subject
    ? Array.isArray(query.subject) ? query.subject : [query.subject]
    : [];

  return ASSETS.filter((asset) => {
    if (query.cls && asset.cls !== query.cls) return false;
    if (query.ratio && !asset.ratios.includes(query.ratio)) return false;
    if (!subjects.every((s) => asset.subject.includes(s))) return false;

    const restrictions = asset.restrictions ?? [];
    if (query.excludeRestricted && restrictions.length) return false;
    // A product context is the one the restriction was written for. Enforced
    // here as well as in tests so the wrong photograph cannot reach a card
    // even in a template nobody thought to test.
    if (query.context === 'product' && restrictions.includes('not-product-imagery')) return false;
    return true;
  });
}

/** The single best match, or null. Never an approximation. */
export function findAsset(query: AssetQuery = {}): Asset | null {
  return findAssets(query)[0] ?? null;
}
