import fs from 'node:fs';
import path from 'node:path';

const source = path.resolve('src/styles/tokens.tokens.json');
const output = path.resolve('public/styles/tokens.css');
const tokens = JSON.parse(fs.readFileSync(source, 'utf8'));
const flat = new Map();

function walk(node, parts = []) {
  if (node && typeof node === 'object' && '$value' in node) {
    flat.set(parts.join('.'), node.$value);
    return;
  }
  for (const [key, value] of Object.entries(node)) if (!key.startsWith('$')) walk(value, [...parts, key]);
}
walk(tokens);

function cssValue(value) {
  if (typeof value === 'string') {
    const alias = value.match(/^\{(.+)\}$/);
    return alias ? `var(--${alias[1].replaceAll('.', '-')})` : value;
  }
  if (Array.isArray(value)) return value.map((item) => item.includes(' ') ? `"${item}"` : item).join(', ');
  if (value && typeof value === 'object' && 'value' in value) return `${value.value}${value.unit}`;
  throw new Error(`Unsupported token value: ${JSON.stringify(value)}`);
}

const body = [...flat].map(([name, value]) => `  --${name.replaceAll('.', '-')}: ${cssValue(value)};`).join('\n');
const css = `/* Generated by scripts/generate-tokens.mjs. Do not edit. */\n:root {\n${body}\n}\n`;

if (process.argv.includes('--check')) {
  if (!fs.existsSync(output) || fs.readFileSync(output, 'utf8') !== css) {
    console.error('public/styles/tokens.css is out of date. Run npm run tokens.');
    process.exit(1);
  }
} else {
  fs.writeFileSync(output, css);
  console.log(`Wrote ${path.relative(process.cwd(), output)}`);
}
